package co.gov.heinsohn.men.parametros.utils;

public class SqlConstants {

	private SqlConstants(){
		// Auto-generated method stub
	}

	public static final String PARAMETROS_FILTROS = "SELECT P.ID, P.APLICACION, P.DOMINIO,  P.DOMINIO_PADRE, P.CODIGO, P.NOMBRE, P.CODIGO_PADRE, P.ESTADO, P.MODIFICABLE, P.TIPO_PARAMETRO ";
	public static final String CONSULTAR_PARAMETROS_FILTROS = PARAMETROS_FILTROS + "FROM PA_PARAMETRO P WHERE P.APLICACION = ?2 AND P.TIPO_PARAMETRO = ?1 ";

	public static final String CONSULTAR_PARAMETROS_NO_MODIFICABLES = PARAMETROS_FILTROS + "FROM PA_PARAMETRO P WHERE P.APLICACION = ?2 AND P.TIPO_PARAMETRO = ?1 AND P.DOMINIO = ?3 AND  P.ESTADO = ?4 AND AND P.MODIFICABLE =?5  ORDER BY P.NOMBRE ASC";

	public static final String CONSULTAR_PARAMETRO_EXISTE = PARAMETROS_FILTROS + "FROM PA_PARAMETRO P WHERE P.APLICACION = ?2 AND P.TIPO_PARAMETRO = ?1 AND P.DOMINIO = ?3 AND  (translate(UPPER(P.NOMBRE), 'ÁÉÍÓÚ', 'AEIOU')) = (translate(UPPER(?4), 'ÁÉÍÓÚ', 'AEIOU')) ORDER BY P.NOMBRE ASC";

	public static final String CONSULTAR_PARAMETROS_FILTROS_DIFERENTES = "SELECT DISTINCT P.DOMINIO, P.APLICACION, P.ESTADO, P.TIPO_PARAMETRO FROM PA_PARAMETRO P WHERE P.APLICACION = ?1 ";

	public static final String FILTRO_TIPO_PARAMETRO = " AND P.TIPO_PARAMETRO = ?2 ";
	
	public static final String  FILTRO_PARAM_DOMINIO = " AND P.DOMINIO = ?3 ";
	
	public static final String FILTRO_ESTADO = " AND  P.ESTADO = ?4 ";
	
	public static final String FILTRO_ORDENAMIENTO = " ORDER BY P.APLICACION ASC ";
	
	public static final String FILTRO_ORDENAMIENTO_NOMBRE = " ORDER BY P.NOMBRE ASC ";
	
	public static final String FILTRO_DOMINIO = "SELECT  DISTINCT P.DOMINIO, P.DESCRIPCION FROM PA_PARAMETRO P WHERE P.APLICACION = ?1 AND P.TIPO_PARAMETRO =?2 ORDER BY P.DOMINIO ASC ";
	
	public static final String FILTRO_TIPO_PARAM = "SELECT  DISTINCT P.TIPO_PARAMETRO FROM PA_PARAMETRO P WHERE P.APLICACION = ? ORDER BY P.TIPO_PARAMETRO ASC ";
	
	public static final String FILTRO_APP = "SELECT  DISTINCT P.APLICACION FROM PA_PARAMETRO P  ORDER BY P.APLICACION ASC ";

	public static final String FILTRO_DEPARTAMENTO = "SELECT  P.NOMBRE, P.CODIGO FROM PA_PARAMETRO P WHERE P.DOMINIO = ? ORDER BY P.NOMBRE ASC ";

}
