
package co.gov.mineducacion.seguridad.web.soap.autenticacion;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "IAutenticacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface IAutenticacion {

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.ObtenerTokenRs
	 * @throws IAutenticacionObtenerTokenMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerToken")
	@WebResult(name = "obtenerTokenRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public ObtenerTokenRs obtenerToken(
			@WebParam(name = "obtenerTokenRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ObtenerTokenRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IAutenticacionObtenerTokenMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IAutenticacionFinalizarSesionMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/finalizarSesion")
	public void finalizarSesion(
			@WebParam(name = "finalizarSesionRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") FinalizarSesionRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IAutenticacionFinalizarSesionMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IAutenticacionModificarPasswordMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/modificarPassword")
	public void modificarPassword(
			@WebParam(name = "modificarPasswordRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ModificarPasswordRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IAutenticacionModificarPasswordMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.ObtenerRolesPermisosRs
	 * @throws IAutenticacionObtenerRolesPermisosMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerRolesPermisos")
	@WebResult(name = "obtenerRolesPermisosRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public ObtenerRolesPermisosRs obtenerRolesPermisos(
			@WebParam(name = "obtenerRolesPermisosRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ObtenerRolesPermisosRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IAutenticacionObtenerRolesPermisosMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.ActualizarFechaVencimientoTokenRs
	 * @throws IAutenticacionActualizarFechaVencimientoTokenMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/actualizarFechaVencimientoToken")
	@WebResult(name = "actualizarFechaVencimientoTokenRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public ActualizarFechaVencimientoTokenRs actualizarFechaVencimientoToken(
			@WebParam(name = "actualizarFechaVencimientoTokenRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarFechaVencimientoTokenRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IAutenticacionActualizarFechaVencimientoTokenMensajeFaultFaultFaultMessage;

}
