# Se debe reemplazar el NombreProyecto por un nombre unico ya que va ser la llave del proyecto
sonar.projectKey=SeguridadApp-SIA3
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
# Se debe poner el token para poder conectarse a sonar, este se genera desde la pagina de sonar.softcaribbean.com
sonar.login=33ca6470d6230cdd9d24f62486683cea29ed3ffb

# En sonar.sources debe ir la ruta padre donde estan los .java si es un proyecto multimodulo se separa por comma las diferente rutas sin espacio
sonar.sources=seguridad-apiRest/src/main/java,seguridad-web/src/main/java 

sonar.java.binaries=**/target/**
# exclusiones de analisis
sonar.exclusions=**/src/test/**,**/servicio/utils/**
# Si tiene lombok implimentado toca descomentarear la siguiente linea y poner la ruta al lombok.jar
# sonar.java.libraries=libraries/lombok.jar

# La ruta donde esta el archivo jacoco.xml para la cobertura de pruebas unitarias, si es multimodulo se debe hacer por cada modulo separado por coma
#sonar.coverage.jacoco.xmlReportPaths=web-apirest/target/site/jacoco/jacoco.xml,dominios/target/site/jacoco/jacoco.xml,servicios/target/site/jacoco/jacoco.xml,dto/target/site/jacoco/jacoco.xml,repositorios/target/site/jacoco/jacoco.xml