
package co.gov.mineducacion.sdk.web.soap.autenticar.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;
import java.util.logging.Level;

import org.apache.log4j.Logger;


import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.mineducacion.sdk.util.FiltroSeguridad;



/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutenticarImplementsService", targetNamespace = "http://autenticacion.soap.web.seguridad.mineducacion.gov.co/", wsdlLocation = "http://192.168.1.53:7001/seguridad-web/AutenticarImplementsService?WSDL")
public class AutenticarImplementsService
    extends Service
{

    private static final Logger logger = Logger.getLogger(AutenticarImplementsService.class.getName());

    private static final Logger LOG = Logger.getLogger(FiltroSeguridad.class.getName());

	private static Properties propiedades = FiltroSeguridad.obtenerPropiedades();
    private static final URL AUTENTICARIMPLEMENTSSERVICE_WSDL_LOCATION;
    private static final WebServiceException AUTENTICARIMPLEMENTSSERVICE_EXCEPTION;
    private static final QName AUTENTICARIMPLEMENTSSERVICE_QNAME = new QName("http://autenticacion.soap.web.seguridad.mineducacion.gov.co/", "AutenticarImplementsService"); //NOSONAR

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            
        	url = new URL(propiedades.getProperty("urlServicio")+propiedades.getProperty("url_wsdl_servicio_autenticacion"));
            logger.info("URL GENERADA: " + url);
            LOG.info("URL Clase AutenticarImplementsService: " + url);

        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTENTICARIMPLEMENTSSERVICE_WSDL_LOCATION = url;
        AUTENTICARIMPLEMENTSSERVICE_EXCEPTION = e;
    }

    public AutenticarImplementsService() {
        super(__getWsdlLocation(), AUTENTICARIMPLEMENTSSERVICE_QNAME);
    }

    public AutenticarImplementsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTENTICARIMPLEMENTSSERVICE_QNAME, features);
    }

    public AutenticarImplementsService(URL wsdlLocation) {
        super(wsdlLocation, AUTENTICARIMPLEMENTSSERVICE_QNAME);
    }

    public AutenticarImplementsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTENTICARIMPLEMENTSSERVICE_QNAME, features);
    }

    public AutenticarImplementsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutenticarImplementsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAutenticacion
     */
    @WebEndpoint(name = "AutenticarImplementsPort")
    public IAutenticacion getAutenticarImplementsPort() {
        return super.getPort(new QName("http://autenticacion.soap.web.seguridad.mineducacion.gov.co/", "AutenticarImplementsPort"), IAutenticacion.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAutenticacion
     */
    @WebEndpoint(name = "AutenticarImplementsPort")
    public IAutenticacion getAutenticarImplementsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://autenticacion.soap.web.seguridad.mineducacion.gov.co/", "AutenticarImplementsPort"), IAutenticacion.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTENTICARIMPLEMENTSSERVICE_EXCEPTION!= null) {
            throw AUTENTICARIMPLEMENTSSERVICE_EXCEPTION;
        }
        return AUTENTICARIMPLEMENTSSERVICE_WSDL_LOCATION;
    }


}
