
package co.gov.mineducacion.sdk.web.soap.autenticar.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;

import co.gov.mineducacion.sdk.web.soap.autenticar.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IAutenticacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IAutenticacion {


    /**
     * 
     * @param aplicacion
     * @param encabezadoSeguridadRq
     * @param parameters
     * @throws IAutenticacionFinalizarSesionMensajeFaultFaultFaultMessage
     */
    @WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/finalizarSesion")
    @Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/finalizarSesion", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/finalizarSesionResponse", fault = {
        @FaultAction(className = IAutenticacionFinalizarSesionMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/finalizarSesion/Fault/IAutenticacionFinalizarSesionMensajeFaultFaultFaultMessage")
    })
    public void finalizarSesion(
        @WebParam(name = "finalizarSesionRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
        FinalizarSesionRq parameters,
        @WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion")
        Aplicacion aplicacion,
        @WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq")
        EncabezadoSeguridad encabezadoSeguridadRq)
        throws IAutenticacionFinalizarSesionMensajeFaultFaultFaultMessage
    ;

    /**
     * 
     * @param aplicacion
     * @param encabezadoSeguridadRq
     * @param parameters
     * @throws IAutenticacionModificarPasswordMensajeFaultFaultFaultMessage
     */
    @WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/modificarPassword")
    @Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/modificarPassword", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/modificarPasswordResponse", fault = {
        @FaultAction(className = IAutenticacionModificarPasswordMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/modificarPassword/Fault/IAutenticacionModificarPasswordMensajeFaultFaultFaultMessage")
    })
    public void modificarPassword(
        @WebParam(name = "modificarPasswordRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
        ModificarPasswordRq parameters,
        @WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion")
        Aplicacion aplicacion,
        @WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq")
        EncabezadoSeguridad encabezadoSeguridadRq)
        throws IAutenticacionModificarPasswordMensajeFaultFaultFaultMessage
    ;

    /**
     * 
     * @param aplicacion
     * @param parameters0
     * @param encabezadoSeguridadRq
     * @param parameters
     * @throws IAutenticacionObtenerTokenMensajeFaultFaultFaultMessage
     */
    @WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerToken")
    @Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerToken", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerTokenResponse", fault = {
        @FaultAction(className = IAutenticacionObtenerTokenMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerToken/Fault/IAutenticacionObtenerTokenMensajeFaultFaultFaultMessage")
    })
    public void obtenerToken(
        @WebParam(name = "obtenerTokenRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
        ObtenerTokenRq parameters,
        @WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion")
        Aplicacion aplicacion,
        @WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq")
        EncabezadoSeguridad encabezadoSeguridadRq,
        @WebParam(name = "obtenerTokenRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", mode = WebParam.Mode.OUT, partName = "parameters")
        Holder<ObtenerTokenRs> parameters0)
        throws IAutenticacionObtenerTokenMensajeFaultFaultFaultMessage
    ;

    /**
     * 
     * @param aplicacion
     * @param parameters0
     * @param encabezadoSeguridadRq
     * @param parameters
     * @throws IAutenticacionActualizarFechaVencimientoTokenMensajeFaultFaultFaultMessage
     */
    @WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/actualizarFechaVencimientoToken")
    @Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/actualizarFechaVencimientoToken", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/actualizarFechaVencimientoTokenResponse", fault = {
        @FaultAction(className = IAutenticacionActualizarFechaVencimientoTokenMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/actualizarFechaVencimientoToken/Fault/IAutenticacionActualizarFechaVencimientoTokenMensajeFaultFaultFaultMessage")
    })
    public void actualizarFechaVencimientoToken(
        @WebParam(name = "actualizarFechaVencimientoTokenRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
        ActualizarFechaVencimientoTokenRq parameters,
        @WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion")
        Aplicacion aplicacion,
        @WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq")
        EncabezadoSeguridad encabezadoSeguridadRq,
        @WebParam(name = "actualizarFechaVencimientoTokenRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", mode = WebParam.Mode.OUT, partName = "parameters")
        Holder<ActualizarFechaVencimientoTokenRs> parameters0)
        throws IAutenticacionActualizarFechaVencimientoTokenMensajeFaultFaultFaultMessage
    ;

    /**
     * 
     * @param aplicacion
     * @param parameters0
     * @param encabezadoSeguridadRq
     * @param parameters
     * @throws IAutenticacionObtenerRolesPermisosMensajeFaultFaultFaultMessage
     */
    @WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerRolesPermisos")
    @Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerRolesPermisos", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerRolesPermisosResponse", fault = {
        @FaultAction(className = IAutenticacionObtenerRolesPermisosMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IAutenticacion/obtenerRolesPermisos/Fault/IAutenticacionObtenerRolesPermisosMensajeFaultFaultFaultMessage")
    })
    public void obtenerRolesPermisos(
        @WebParam(name = "obtenerRolesPermisosRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
        ObtenerRolesPermisosRq parameters,
        @WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion")
        Aplicacion aplicacion,
        @WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq")
        EncabezadoSeguridad encabezadoSeguridadRq,
        @WebParam(name = "obtenerRolesPermisosRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", mode = WebParam.Mode.OUT, partName = "parameters")
        Holder<ObtenerRolesPermisosRs> parameters0)
        throws IAutenticacionObtenerRolesPermisosMensajeFaultFaultFaultMessage
    ;

}
