
package co.gov.mineducacion.sdk.web.soap.gestionar.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.Properties;

import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import co.gov.mineducacion.sdk.util.FiltroSeguridad;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionarUsuariosImplementsService", targetNamespace = "http://gestionar.soap.web.seguridad.mineducacion.gov.co/", wsdlLocation = "http://localhost:7001/seguridad-web/GestionarUsuariosImplementsService?wsdl")
public class GestionarUsuariosImplementsService
    extends Service
{
    private static final Logger logger = Logger.getLogger(GestionarUsuariosImplementsService.class.getName());
    private static final String URL_BASE = "http://gestionar.soap.web.seguridad.mineducacion.gov.co/";

	private static Properties propiedades = FiltroSeguridad.obtenerPropiedades();
    private static final URL GESTIONARUSUARIOSIMPLEMENTSSERVICE_WSDL_LOCATION;
    private static final WebServiceException GESTIONARUSUARIOSIMPLEMENTSSERVICE_EXCEPTION;
    private static final QName GESTIONARUSUARIOSIMPLEMENTSSERVICE_QNAME = new QName(URL_BASE, "GestionarUsuariosImplementsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            
            url = new URL(propiedades.getProperty("urlServicio")+propiedades.getProperty("url_wsdl_servicio_gestion_usuarios"));
            //url = new URL("http://localhost:7001/"+"seguridad-web/GestionarUsuariosImplementsService?WSDL"); //NOSONAR
            logger.info("URL GENERADA: " + url); //NOSONAR

        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONARUSUARIOSIMPLEMENTSSERVICE_WSDL_LOCATION = url;
        GESTIONARUSUARIOSIMPLEMENTSSERVICE_EXCEPTION = e;
    }

    public GestionarUsuariosImplementsService() {
        super(__getWsdlLocation(), GESTIONARUSUARIOSIMPLEMENTSSERVICE_QNAME);
    }

    public GestionarUsuariosImplementsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), GESTIONARUSUARIOSIMPLEMENTSSERVICE_QNAME, features);
    }

    public GestionarUsuariosImplementsService(URL wsdlLocation) {
        super(wsdlLocation, GESTIONARUSUARIOSIMPLEMENTSSERVICE_QNAME);
    }

    public GestionarUsuariosImplementsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONARUSUARIOSIMPLEMENTSSERVICE_QNAME, features);
    }

    public GestionarUsuariosImplementsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionarUsuariosImplementsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGestionarUsuario
     */
    @WebEndpoint(name = "GestionarUsuariosImplementsPort")
    public IGestionarUsuario getGestionarUsuariosImplementsPort() {
        return super.getPort(new QName(URL_BASE, "GestionarUsuariosImplementsPort"), IGestionarUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGestionarUsuario
     */
    @WebEndpoint(name = "GestionarUsuariosImplementsPort")
    public IGestionarUsuario getGestionarUsuariosImplementsPort(WebServiceFeature... features) {
        return super.getPort(new QName(URL_BASE, "GestionarUsuariosImplementsPort"), IGestionarUsuario.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GESTIONARUSUARIOSIMPLEMENTSSERVICE_EXCEPTION!= null) {
            throw GESTIONARUSUARIOSIMPLEMENTSSERVICE_EXCEPTION;
        }
        return GESTIONARUSUARIOSIMPLEMENTSSERVICE_WSDL_LOCATION;
    }

}
