
package co.gov.mineducacion.sdk.web.soap.gestionar.servicio;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.Holder;

import co.gov.mineducacion.sdk.web.soap.gestionar.*;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "IGestionarUsuario", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface IGestionarUsuario {

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioInactivarUsuarioMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/inactivarUsuario")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/inactivarUsuario", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/inactivarUsuarioResponse", fault = {
			@FaultAction(className = IGestionarUsuarioInactivarUsuarioMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/inactivarUsuario/Fault/IGestionarUsuarioInactivarUsuarioMensajeFaultFaultFaultMessage") })
	public void inactivarUsuario(
			@WebParam(name = "inactivarUsuarioRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") InactivarUsuarioRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioInactivarUsuarioMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param parameters0
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioCrearUsuarioExternoMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/crearUsuarioExterno")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/crearUsuarioExterno", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/crearUsuarioExternoResponse", fault = {
			@FaultAction(className = IGestionarUsuarioCrearUsuarioExternoMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/crearUsuarioExterno/Fault/IGestionarUsuarioCrearUsuarioExternoMensajeFaultFaultFaultMessage") })
	public void crearUsuarioExterno(
			@WebParam(name = "crearUsuarioExternoRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") CrearUsuarioExternoRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq,
			@WebParam(name = "crearUsuarioExternoRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", mode = WebParam.Mode.OUT, partName = "parameters") Holder<CrearUsuarioExternoRs> parameters0)
			throws IGestionarUsuarioCrearUsuarioExternoMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioModificarUsuarioExternoMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/modificarUsuarioExterno")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/modificarUsuarioExterno", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/modificarUsuarioExternoResponse", fault = {
			@FaultAction(className = IGestionarUsuarioModificarUsuarioExternoMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/modificarUsuarioExterno/Fault/IGestionarUsuarioModificarUsuarioExternoMensajeFaultFaultFaultMessage") })
	public void modificarUsuarioExterno(
			@WebParam(name = "modificarUsuarioExternoRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ModificarUsuarioExternoRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioModificarUsuarioExternoMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param parameters0
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuariosRol")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuariosRol", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuariosRolResponse", fault = {
			@FaultAction(className = IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuariosRol/Fault/IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage") })
	public void consultarUsuariosRol(
			@WebParam(name = "consultarUsuariosRolRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ConsultarUsuariosRolRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq,
			@WebParam(name = "consultarUsuariosRolRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", mode = WebParam.Mode.OUT, partName = "parameters") Holder<ConsultarUsuariosRolRs> parameters0)
			throws IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioDesvincularRolesUsuarioMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/desvincularRolesUsuario")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/desvincularRolesUsuario", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/desvincularRolesUsuarioResponse", fault = {
			@FaultAction(className = IGestionarUsuarioDesvincularRolesUsuarioMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/desvincularRolesUsuario/Fault/IGestionarUsuarioDesvincularRolesUsuarioMensajeFaultFaultFaultMessage") })
	public void desvincularRolesUsuario(
			@WebParam(name = "desvincularRolesUsuarioRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") DesvincularRolesUsuarioRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioDesvincularRolesUsuarioMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioVincularRolesUsuarioMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/vincularRolesUsuario")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/vincularRolesUsuario", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/vincularRolesUsuarioResponse", fault = {
			@FaultAction(className = IGestionarUsuarioVincularRolesUsuarioMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuariosRol/Fault/IGestionarUsuarioVincularRolesUsuarioMensajeFaultFaultFaultMessage") })
	public void vincularRolesUsuario(
			@WebParam(name = "vincularRolesUsuarioRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") VincularRolesUsuarioRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioVincularRolesUsuarioMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioActualizarEmailMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarEmail")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarEmail", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarEmailResponse", fault = {
			@FaultAction(className = IGestionarUsuarioActualizarEmailMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarEmail/Fault/IGestionarUsuarioActualizarEmailMensajeFaultFaultFaultMessage")
	})
	public void actualizarEmail(
			@WebParam(name = "ActualizarEmailRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarEmailRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioActualizarEmailMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizardatosbasicos")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizardatosbasicos", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizardatosbasicosResponse", fault = {
			@FaultAction(className = IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarEmail/Fault/IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage")
	})
	public void actualizarDatosBasicos(
			@WebParam(name = "ActualizarDatosBasicosRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarDatosBasicosRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioActualizarPasswordMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarPassword")
	@Action(input = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarPassword", output = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarPasswordResponse", fault = {
			@FaultAction(className = IGestionarUsuarioActualizarPasswordMensajeFaultFaultFaultMessage.class, value = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarPassword/Fault/IGestionarUsuarioActualizarPasswordMensajeFaultFaultFaultMessage")
	})
	public void actualizarPassword(
			@WebParam(name = "ActualizarPasswordRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarPasswordRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioActualizarPasswordMensajeFaultFaultFaultMessage;
}
