
package co.gov.mineducacion.seguridad.web.soap.gestionar;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GestionarUsuario", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", wsdlLocation = "file:/C:/Users/Administrador/Desktop/Hoy/Proyectos/WorkSpace/Seguridad/seguridad-ejb/src/wsdl/Gestionar/sia3.wsdl")
public class GestionarUsuario
    extends Service
{

    private static final URL GESTIONARUSUARIO_WSDL_LOCATION;
    private static final WebServiceException GESTIONARUSUARIO_EXCEPTION;
    private static final QName GESTIONARUSUARIO_QNAME = new QName("http://soap.mineducacion.gov.co/11/seguridad/sia3", "GestionarUsuario"); // NOSONAR

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Administrador/Desktop/Hoy/Proyectos/WorkSpace/Seguridad/seguridad-ejb/src/wsdl/Gestionar/sia3.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        GESTIONARUSUARIO_WSDL_LOCATION = url;
        GESTIONARUSUARIO_EXCEPTION = e;
    }

    public GestionarUsuario() {
        super(getWsdlLocation(), GESTIONARUSUARIO_QNAME);
    }

    public GestionarUsuario(WebServiceFeature... features) {
        super(getWsdlLocation(), GESTIONARUSUARIO_QNAME, features);
    }

    public GestionarUsuario(URL wsdlLocation) {
        super(wsdlLocation, GESTIONARUSUARIO_QNAME);
    }

    public GestionarUsuario(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GESTIONARUSUARIO_QNAME, features);
    }

    public GestionarUsuario(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionarUsuario(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IGestionarUsuario
     */
    @WebEndpoint(name = "BasicHttpBinding_IGestionarUsuario")
    public IGestionarUsuario getBasicHttpBindingIGestionarUsuario() {
        return super.getPort(new QName("http://soap.mineducacion.gov.co/11/seguridad/sia3", "BasicHttpBinding_IGestionarUsuario"), IGestionarUsuario.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IGestionarUsuario
     */
    @WebEndpoint(name = "BasicHttpBinding_IGestionarUsuario")
    public IGestionarUsuario getBasicHttpBindingIGestionarUsuario(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.mineducacion.gov.co/11/seguridad/sia3", "BasicHttpBinding_IGestionarUsuario"), IGestionarUsuario.class, features);
    }

    private static URL getWsdlLocation() {
        if (GESTIONARUSUARIO_EXCEPTION!= null) {
            throw GESTIONARUSUARIO_EXCEPTION;
        }
        return GESTIONARUSUARIO_WSDL_LOCATION;
    }

}
