
package co.gov.mineducacion.seguridad.web.soap.gestionar;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "IGestionarUsuario", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({ ObjectFactory.class })
public interface IGestionarUsuario {

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.CrearUsuarioExternoRs
	 * @throws IGestionarUsuarioCrearUsuarioExternoMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/crearUsuarioExterno")
	@WebResult(name = "crearUsuarioExternoRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public CrearUsuarioExternoRs crearUsuarioExterno(
			@WebParam(name = "crearUsuarioExternoRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") CrearUsuarioExternoRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioCrearUsuarioExternoMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioModificarUsuarioExternoMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/modificarUsuarioExterno")
	public void modificarUsuarioExterno(
			@WebParam(name = "modificarUsuarioExternoRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ModificarUsuarioExternoRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioModificarUsuarioExternoMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.ConsultarUsuariosRolRs
	 * @throws IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuariosRol")
	@WebResult(name = "consultarUsuariosRolRs", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public ConsultarUsuariosRolRs consultarUsuariosRol(
			@WebParam(name = "consultarUsuariosRolRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ConsultarUsuariosRolRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage;

	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioInactivarUsuarioMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/inactivarUsuario")
	public void inactivarUsuario(
			@WebParam(name = "inactivarUsuarioRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") InactivarUsuarioRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioInactivarUsuarioMensajeFaultFaultFaultMessage;
	
	/**
	 * 
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.ConsultarUsuariosRolRs
	 * @throws IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/consultarUsuarioLogon")
	@WebResult(name = "consultarUsuarioLogon", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public ConsultarUsuariosRolRs consultarUsuarioLogon(
			@WebParam(name = "consultarUsuariosRolRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ConsultarUsuariosRolRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioConsultarUsuariosRolMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 *         co.gov.mineducacion.soap._11.seguridad.sia3.desvincularRolesUsuario
	 * @throws IGestionarUsuarioDesvincularRolesUsuarioMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/desvincularRolesUsuario")
	@WebResult(name = "desvincularRolesUsuario", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public void desvincularRolesUsuario(
			@WebParam(name = "desvincularRolesUsuarioRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") DesvincularRolesUsuarioRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioDesvincularRolesUsuarioMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @return returns
	 * 			 co.gov.mineducacion.soap._11.seguridad.sia3.vincularRolesUsuario
	 * @throws IGestionarUsuarioVincularRolesUsuarioMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/vincularRolesUsuario")
	@WebResult(name = "vincularRolesUsuario", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public void vincularRolesUsuario(
			@WebParam(name = "vincularRolesUsuarioRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") VincularRolesUsuarioRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioVincularRolesUsuarioMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioActualizarEmailMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarEmail")
	@WebResult(name = "actualizarEmail", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public void actualizarEmail(
			@WebParam(name = "ActualizarEmailRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarEmailRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioActualizarEmailMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizardatosbasicos")
	@WebResult(name = "actualizarDatosBasicos", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public void actualizarDatosBasicos(
			@WebParam(name = "ActualizarDatosBasicosRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarDatosBasicosRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage;

	/**
	 *
	 * @param aplicacion
	 * @param encabezadoSeguridadRq
	 * @param parameters
	 * @throws IGestionarUsuarioActualizarPasswordMensajeFaultFaultFaultMessage
	 */
	@WebMethod(action = "http://soap.mineducacion.gov.co/11/seguridad/sia3/IGestionarUsuario/actualizarPassword")
	@WebResult(name = "actualizarPassword", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters")
	public void actualizarPassword(
			@WebParam(name = "ActualizarPasswordRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", partName = "parameters") ActualizarPasswordRq parameters,
			@WebParam(name = "aplicacion", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "aplicacion") Aplicacion aplicacion,
			@WebParam(name = "encabezadoSeguridadRq", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3", header = true, partName = "encabezadoSeguridadRq") EncabezadoSeguridad encabezadoSeguridadRq)
			throws IGestionarUsuarioActualizarPasswordMensajeFaultFaultFaultMessage;

}
