package co.gov.mineducacion.seguridad.web.soap.gestionar;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 *
 */

@WebFault(name = "mensajeFault", targetNamespace = "http://soap.mineducacion.gov.co/11/seguridad/sia3")
public class IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage extends Exception {
    /**
     *
     * @author lgrajales
     */
    private static final long serialVersionUID = 1L;
    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private final transient MensajeFault faultInfo;

    /**
     *
     * @param message
     * @param faultInfo
     */
    public IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage(String message, MensajeFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IGestionarUsuarioActualizarDatosBasicosMensajeFaultFaultFaultMessage(String message, MensajeFault faultInfo,
                                                                                Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return returns fault bean:
     *         co.gov.mineducacion.soap._11.seguridad.sia3.MensajeFault
     */
    public MensajeFault getFaultInfo() {
        return faultInfo;
    }
}
